[package]
name = "manget_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
log = "0.4.17"
manget = { version = "0.1.0", path = "../manget" }
simple_logger = "4.1.0"
tokio = { version = "1.28.1", features = ["macros"] }
